### ISSUE TITLE
Expected non-alpha return values don't make sense.

### ISSUE THREAD

**Issue by tildebyte** [CheckiO-Missions/checkio-mission-all-upper#6]
"If the string is empty or doesn't have any letter in it - function should return True"

This just doesn't make sense to me; given everything else about this mission, I feel like the return for inputs e.g. `''` or '`1230 '` should be `False`. We're checking for "all upper", and neither an empty string nor an all-numeric string can *possibly even be* uppercase, so...

Regardless of my feeling about it, it makes the task unnecessarily complicated.

What is worse is that the "string with no letter in it" case isn't even included in the self-check assertions; so it's really easy to miss this acceptance criteria.

**Comment by oduvan** [comment]
https://github.com/CheckiO-Missions/checkio-mission-all-upper/blob/master/editor/initial_code/python_3#L16 - assert with no letter
